-- LottoBank 전체 서비스 데이터와 권한을 구성하는 통합 스키마

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.lottery_stores (
  id text primary key,
  name text not null,
  address text not null,
  region text,
  lat double precision,
  lng double precision,
  approved boolean not null default false,
  scan_count bigint not null default 0,
  first_scanned_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_lottery_stores (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  address text not null,
  created_at timestamptz not null default now(),
  unique (user_id, name, address)
);

create table if not exists public.tickets (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  qr_url text not null unique,
  round_no integer,
  numbers integer[] not null default '{}',
  game_count integer not null default 1,
  purchase_date date,
  result text not null default 'pending',
  prize_rank integer,
  prize_amount bigint not null default 0,
  lottery_type text not null default 'lotto',
  purchase_channel text not null default 'retail',
  purchase_mode text,
  matched_count integer,
  total_number_count integer not null default 6,
  user_store_id uuid references public.user_lottery_stores(id) on delete set null,
  store_id text,
  store_name text,
  store_address text,
  store_lat double precision,
  store_lng double precision,
  created_at timestamptz not null default now()
);

create table if not exists public.user_stats (
  user_id uuid primary key references auth.users(id) on delete cascade,
  total_tickets integer not null default 0,
  total_spent bigint not null default 0,
  total_wins integer not null default 0,
  total_prize bigint not null default 0,
  best_rank integer,
  rank_1_count integer not null default 0,
  rank_2_count integer not null default 0,
  rank_3_count integer not null default 0,
  rank_4_count integer not null default 0,
  rank_5_count integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.user_badges (
  user_id uuid not null references auth.users(id) on delete cascade,
  badge_id text not null,
  earned_at timestamptz not null default now(),
  primary key (user_id, badge_id)
);

create table if not exists public.activity_feed (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  nick text not null,
  type text not null,
  data jsonb not null default '{}',
  created_at timestamptz not null default now()
);

create table if not exists public.chat_messages (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  nickname text not null,
  verified_title text,
  message text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.posts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  nickname text not null,
  tag text,
  title text not null,
  body text,
  likes integer not null default 0,
  comment_count integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.comments (
  id uuid primary key default gen_random_uuid(),
  post_id uuid references public.posts(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  nickname text not null,
  body text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.post_likes (
  post_id uuid references public.posts(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create table if not exists public.ranking_snapshots (
  id bigint generated by default as identity primary key,
  period_key text not null,
  ranking_type text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  rank integer not null check (rank > 0),
  score numeric not null default 0,
  title text not null,
  badge_icon text,
  border_color text,
  created_at timestamptz not null default now(),
  unique (period_key, ranking_type, user_id)
);

create table if not exists public.user_system_titles (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title_type text not null,
  title text not null,
  lottery_type text,
  round_no integer,
  prize_rank integer,
  period_key text,
  badge_icon text,
  border_color text,
  active boolean not null default true,
  awarded_at timestamptz not null default now(),
  expires_at timestamptz,
  unique (user_id, title_type, title, period_key)
);

create table if not exists public.user_daily_visits (
  user_id uuid not null references auth.users(id) on delete cascade,
  visit_date date not null default current_date,
  first_visited_at timestamptz not null default now(),
  last_visited_at timestamptz not null default now(),
  primary key (user_id, visit_date)
);

alter table public.lottery_stores add column if not exists approved boolean not null default false;
alter table public.tickets
  add column if not exists game_count integer not null default 1,
  add column if not exists lottery_type text not null default 'lotto',
  add column if not exists purchase_channel text not null default 'retail',
  add column if not exists purchase_mode text,
  add column if not exists matched_count integer,
  add column if not exists total_number_count integer not null default 6,
  add column if not exists user_store_id uuid references public.user_lottery_stores(id) on delete set null,
  add column if not exists store_id text,
  add column if not exists store_name text,
  add column if not exists store_address text,
  add column if not exists store_lat double precision,
  add column if not exists store_lng double precision;
alter table public.chat_messages add column if not exists verified_title text;

create index if not exists idx_tickets_user_round on public.tickets (user_id, round_no desc);
create index if not exists idx_user_stores_user on public.user_lottery_stores (user_id, created_at desc);
create index if not exists idx_rankings_period on public.ranking_snapshots (period_key, ranking_type, rank);
create index if not exists idx_titles_user_active on public.user_system_titles (user_id, active, awarded_at desc);
create index if not exists idx_lottery_stores_location on public.lottery_stores (lat, lng) where approved = true;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, nickname)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'nickname', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  insert into public.user_stats (user_id) values (new.id) on conflict (user_id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

do $$
declare
  table_name text;
  policy_name text := 'LottoBank 관리자 전체 권한';
begin
  foreach table_name in array array[
    'profiles','lottery_stores','user_lottery_stores','tickets','user_stats','user_badges',
    'activity_feed','chat_messages','posts','comments','post_likes','ranking_snapshots',
    'user_system_titles','user_daily_visits'
  ]
  loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('drop policy if exists %I on public.%I', policy_name, table_name);
    execute format(
      'create policy %I on public.%I for all to authenticated using ((select auth.jwt() ->> ''email'') = ''jobdevil23@gmail.com'') with check ((select auth.jwt() ->> ''email'') = ''jobdevil23@gmail.com'')',
      policy_name,
      table_name
    );
  end loop;
end
$$;

drop policy if exists "프로필 공개 조회" on public.profiles;
create policy "프로필 공개 조회" on public.profiles for select using (true);
drop policy if exists "본인 프로필 수정" on public.profiles;
create policy "본인 프로필 수정" on public.profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "승인 판매점 공개 조회" on public.lottery_stores;
create policy "승인 판매점 공개 조회" on public.lottery_stores for select using (approved = true);

drop policy if exists "본인 판매점 관리" on public.user_lottery_stores;
create policy "본인 판매점 관리" on public.user_lottery_stores for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "본인 티켓 관리" on public.tickets;
create policy "본인 티켓 관리" on public.tickets for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "전적 공개 조회" on public.user_stats;
create policy "전적 공개 조회" on public.user_stats for select using (true);
drop policy if exists "본인 전적 관리" on public.user_stats;
create policy "본인 전적 관리" on public.user_stats for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "뱃지 공개 조회" on public.user_badges;
create policy "뱃지 공개 조회" on public.user_badges for select using (true);
drop policy if exists "본인 뱃지 등록" on public.user_badges;
create policy "본인 뱃지 등록" on public.user_badges for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "활동 공개 조회" on public.activity_feed;
create policy "활동 공개 조회" on public.activity_feed for select using (true);
drop policy if exists "본인 활동 등록" on public.activity_feed;
create policy "본인 활동 등록" on public.activity_feed for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "채팅 공개 조회" on public.chat_messages;
create policy "채팅 공개 조회" on public.chat_messages for select using (true);
drop policy if exists "본인 채팅 등록" on public.chat_messages;
create policy "본인 채팅 등록" on public.chat_messages for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "본인 채팅 삭제" on public.chat_messages;
create policy "본인 채팅 삭제" on public.chat_messages for delete to authenticated using (auth.uid() = user_id);

drop policy if exists "게시글 공개 조회" on public.posts;
create policy "게시글 공개 조회" on public.posts for select using (true);
drop policy if exists "본인 게시글 관리" on public.posts;
create policy "본인 게시글 관리" on public.posts for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "댓글 공개 조회" on public.comments;
create policy "댓글 공개 조회" on public.comments for select using (true);
drop policy if exists "본인 댓글 관리" on public.comments;
create policy "본인 댓글 관리" on public.comments for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "좋아요 공개 조회" on public.post_likes;
create policy "좋아요 공개 조회" on public.post_likes for select using (true);
drop policy if exists "본인 좋아요 관리" on public.post_likes;
create policy "본인 좋아요 관리" on public.post_likes for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "랭킹 공개 조회" on public.ranking_snapshots;
create policy "랭킹 공개 조회" on public.ranking_snapshots for select using (true);
drop policy if exists "칭호 공개 조회" on public.user_system_titles;
create policy "칭호 공개 조회" on public.user_system_titles for select using (true);
drop policy if exists "본인 출석 관리" on public.user_daily_visits;
create policy "본인 출석 관리" on public.user_daily_visits for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'chat_messages') then
    alter publication supabase_realtime add table public.chat_messages;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'activity_feed') then
    alter publication supabase_realtime add table public.activity_feed;
  end if;
end
$$;
