-- 월간 랭킹, 명예의 전당, 판매점 지도 데이터를 저장하는 확장 스키마

alter table public.tickets
  add column if not exists lottery_type text default 'lotto',
  add column if not exists purchase_channel text default 'retail',
  add column if not exists purchase_mode text,
  add column if not exists matched_count integer,
  add column if not exists total_number_count integer default 6,
  add column if not exists store_id text,
  add column if not exists store_name text,
  add column if not exists store_address text,
  add column if not exists store_lat double precision,
  add column if not exists store_lng double precision,
  add column if not exists game_numbers jsonb not null default '[]'::jsonb,
  add column if not exists qr_payload text,
  add column if not exists pension_group integer,
  add column if not exists pension_number text,
  add column if not exists serial_meta text,
  add column if not exists game_results jsonb not null default '[]'::jsonb;

alter table public.chat_messages
  add column if not exists monthly_badges jsonb not null default '[]'::jsonb;

alter table public.profiles
  add column if not exists selected_rank_badges jsonb not null default '[]'::jsonb;

create table if not exists public.saved_number_sets (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  lottery_type text not null check (lottery_type in ('lotto','pension')),
  round_no integer not null,
  numbers integer[] not null default '{}',
  pension_group integer,
  pension_number text,
  created_at timestamptz not null default now()
);

alter table public.saved_number_sets enable row level security;
drop policy if exists "users manage own saved numbers" on public.saved_number_sets;
create policy "users manage own saved numbers"
  on public.saved_number_sets for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create index if not exists idx_saved_number_sets_user_round
  on public.saved_number_sets (user_id, lottery_type, round_no desc);

drop policy if exists "admin deletes activity feed" on public.activity_feed;
create policy "admin deletes activity feed"
  on public.activity_feed for delete to authenticated
  using ((select auth.jwt() ->> 'email') = 'jobdevil23@gmail.com' or auth.uid() = user_id);

create table if not exists public.lottery_stores (
  id text primary key,
  name text not null,
  address text not null,
  region text,
  lat double precision,
  lng double precision,
  scan_count bigint not null default 0,
  first_scanned_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ticket_game_stores (
  ticket_id uuid not null references public.tickets(id) on delete cascade,
  game_index integer not null check (game_index >= 0),
  user_id uuid not null references auth.users(id) on delete cascade,
  store_id text not null references public.lottery_stores(id) on delete restrict,
  created_at timestamptz not null default now(),
  primary key (ticket_id, game_index)
);

alter table public.ticket_game_stores enable row level security;
drop policy if exists "users manage own ticket game stores" on public.ticket_game_stores;
create policy "users manage own ticket game stores"
  on public.ticket_game_stores for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create table if not exists public.ranking_snapshots (
  id bigint generated by default as identity primary key,
  period_key text not null,
  ranking_type text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  rank integer not null check (rank > 0),
  score numeric not null default 0,
  title text not null,
  badge_icon text,
  border_color text,
  created_at timestamptz not null default now(),
  unique (period_key, ranking_type, user_id)
);

create table if not exists public.user_daily_visits (
  user_id uuid not null references auth.users(id) on delete cascade,
  visit_date date not null default current_date,
  first_visited_at timestamptz not null default now(),
  last_visited_at timestamptz not null default now(),
  primary key (user_id, visit_date)
);

create table if not exists public.user_system_titles (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title_type text not null,
  title text not null,
  lottery_type text,
  round_no integer,
  prize_rank integer,
  period_key text,
  badge_icon text,
  border_color text,
  active boolean not null default true,
  awarded_at timestamptz not null default now(),
  expires_at timestamptz,
  unique (user_id, title_type, title, period_key)
);

create index if not exists idx_ranking_snapshots_period
  on public.ranking_snapshots (period_key, ranking_type, rank);
create index if not exists idx_user_system_titles_active
  on public.user_system_titles (user_id, active, awarded_at desc);
create index if not exists idx_lottery_stores_location
  on public.lottery_stores (lat, lng);
create index if not exists idx_tickets_ranking_fields
  on public.tickets (purchase_date, user_id, prize_rank, store_id);

alter table public.lottery_stores enable row level security;
alter table public.ranking_snapshots enable row level security;
alter table public.user_system_titles enable row level security;
alter table public.user_daily_visits enable row level security;

drop policy if exists "lottery stores are public" on public.lottery_stores;
create policy "lottery stores are public"
  on public.lottery_stores for select using (true);

drop policy if exists "ranking snapshots are public" on public.ranking_snapshots;
create policy "ranking snapshots are public"
  on public.ranking_snapshots for select using (true);

drop policy if exists "system titles are public" on public.user_system_titles;
create policy "system titles are public"
  on public.user_system_titles for select using (true);

drop policy if exists "users manage own daily visits" on public.user_daily_visits;
create policy "users manage own daily visits"
  on public.user_daily_visits for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create or replace function public.refresh_monthly_rankings()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  current_period text := to_char(timezone('Asia/Seoul', now()), 'YYYY-MM');
begin
  delete from public.ranking_snapshots
  where period_key = current_period
    and ranking_type in ('purchase','accuracy','efficiency','miss','pioneer');

  insert into public.ranking_snapshots
    (period_key, ranking_type, user_id, rank, score, title, badge_icon, border_color)
  with ticket_scored as (
    select
      ticket.*,
      case when jsonb_array_length(coalesce(game_results, '[]'::jsonb)) > 0
        then (select coalesce(sum((item ->> 'matched')::numeric), 0) from jsonb_array_elements(game_results) item)
        else coalesce(matched_count, 0)::numeric
      end as ticket_matches,
      case when jsonb_array_length(coalesce(game_results, '[]'::jsonb)) > 0
        then (select count(*)::numeric from jsonb_array_elements(game_results) item where coalesce((item ->> 'matched')::integer, 0) = 0)
        else case when coalesce(matched_count, 0) = 0 then greatest(coalesce(game_count, 1), 1) else 0 end::numeric
      end as ticket_misses
    from public.tickets ticket
    where to_char(coalesce(purchase_date, (created_at at time zone 'Asia/Seoul')::date), 'YYYY-MM') = current_period
  ),
  ticket_base as (
    select
      user_id,
      sum(greatest(coalesce(game_count, 1), 1) * 1000)::numeric as spent,
      sum(coalesce(prize_amount, 0))::numeric as prize,
      sum(ticket_matches)::numeric as matches,
      sum(ticket_misses)::numeric as misses
    from ticket_scored
    group by user_id
  ),
  scores as (
    select user_id, metric.ranking_type, metric.score
    from ticket_base
    cross join lateral (values
      ('purchase', spent),
      ('accuracy', matches),
      ('efficiency', case when spent > 0 then round(prize * 100 / spent, 4) else 0 end),
      ('miss', misses)
    ) as metric(ranking_type, score)
    where metric.score > 0
  ),
  ranked as (
    select
      user_id,
      ranking_type,
      score,
      dense_rank() over (partition by ranking_type order by score desc)::integer as rank
    from scores
  )
  select
    current_period,
    ranking_type,
    user_id,
    rank,
    score,
    case ranking_type
      when 'purchase' then '구매'
      when 'accuracy' then '저격'
      when 'efficiency' then '수익'
      else '똥손'
    end,
    case ranking_type
      when 'purchase' then '👑'
      when 'accuracy' then '🎯'
      when 'efficiency' then '💸'
      else '💩'
    end,
    '#f5c451'
  from ranked;
end;
$$;

create or replace function public.refresh_monthly_rankings_after_ticket()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.refresh_monthly_rankings();
  return null;
end;
$$;

drop trigger if exists refresh_monthly_rankings_on_ticket on public.tickets;
create trigger refresh_monthly_rankings_on_ticket
  after insert or update or delete on public.tickets
  for each statement execute function public.refresh_monthly_rankings_after_ticket();

grant execute on function public.refresh_monthly_rankings() to authenticated;
