-- 월간 랭킹, 명예의 전당, 판매점 지도 데이터를 저장하는 확장 스키마

alter table public.tickets
  add column if not exists lottery_type text default 'lotto',
  add column if not exists purchase_channel text default 'retail',
  add column if not exists purchase_mode text,
  add column if not exists matched_count integer,
  add column if not exists total_number_count integer default 6,
  add column if not exists store_id text,
  add column if not exists store_name text,
  add column if not exists store_address text,
  add column if not exists store_lat double precision,
  add column if not exists store_lng double precision,
  add column if not exists game_numbers jsonb not null default '[]'::jsonb,
  add column if not exists qr_payload text,
  add column if not exists pension_group integer,
  add column if not exists pension_number text,
  add column if not exists serial_meta text,
  add column if not exists ticket_code text,
  add column if not exists game_results jsonb not null default '[]'::jsonb;

create unique index if not exists idx_tickets_ticket_code_unique
  on public.tickets (ticket_code)
  where ticket_code is not null;

alter table public.chat_messages
  add column if not exists monthly_badges jsonb not null default '[]'::jsonb;

alter table public.profiles
  add column if not exists selected_rank_badges jsonb not null default '[]'::jsonb;

create table if not exists public.saved_number_sets (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  lottery_type text not null check (lottery_type in ('lotto','pension')),
  round_no integer not null,
  numbers integer[] not null default '{}',
  pension_group integer,
  pension_number text,
  created_at timestamptz not null default now()
);

alter table public.saved_number_sets enable row level security;
drop policy if exists "users manage own saved numbers" on public.saved_number_sets;
create policy "users manage own saved numbers"
  on public.saved_number_sets for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create index if not exists idx_saved_number_sets_user_round
  on public.saved_number_sets (user_id, lottery_type, round_no desc);

drop policy if exists "admin deletes activity feed" on public.activity_feed;
create policy "admin deletes activity feed"
  on public.activity_feed for delete to authenticated
  using ((select auth.jwt() ->> 'email') = 'jobdevil23@gmail.com' or auth.uid() = user_id);

create table if not exists public.lottery_stores (
  id text primary key,
  name text not null,
  address text not null,
  region text,
  lat double precision,
  lng double precision,
  scan_count bigint not null default 0,
  first_scanned_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ticket_game_stores (
  ticket_id uuid not null references public.tickets(id) on delete cascade,
  game_index integer not null check (game_index >= 0),
  user_id uuid not null references auth.users(id) on delete cascade,
  store_id text not null references public.lottery_stores(id) on delete restrict,
  created_at timestamptz not null default now(),
  primary key (ticket_id, game_index)
);

alter table public.ticket_game_stores enable row level security;
drop policy if exists "users manage own ticket game stores" on public.ticket_game_stores;
create policy "users manage own ticket game stores"
  on public.ticket_game_stores for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create table if not exists public.ranking_snapshots (
  id bigint generated by default as identity primary key,
  period_key text not null,
  ranking_type text not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  rank integer not null check (rank > 0),
  score numeric not null default 0,
  title text not null,
  badge_icon text,
  border_color text,
  created_at timestamptz not null default now(),
  unique (period_key, ranking_type, user_id)
);

create table if not exists public.user_daily_visits (
  user_id uuid not null references auth.users(id) on delete cascade,
  visit_date date not null default current_date,
  first_visited_at timestamptz not null default now(),
  last_visited_at timestamptz not null default now(),
  primary key (user_id, visit_date)
);

create table if not exists public.user_system_titles (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title_type text not null,
  title text not null,
  lottery_type text,
  round_no integer,
  prize_rank integer,
  period_key text,
  badge_icon text,
  border_color text,
  active boolean not null default true,
  awarded_at timestamptz not null default now(),
  expires_at timestamptz,
  unique (user_id, title_type, title, period_key)
);

create index if not exists idx_ranking_snapshots_period
  on public.ranking_snapshots (period_key, ranking_type, rank);
create index if not exists idx_user_system_titles_active
  on public.user_system_titles (user_id, active, awarded_at desc);
create index if not exists idx_lottery_stores_location
  on public.lottery_stores (lat, lng);
create index if not exists idx_tickets_ranking_fields
  on public.tickets (purchase_date, user_id, prize_rank, store_id);

alter table public.lottery_stores enable row level security;
alter table public.ranking_snapshots enable row level security;
alter table public.user_system_titles enable row level security;
alter table public.user_daily_visits enable row level security;

drop policy if exists "lottery stores are public" on public.lottery_stores;
create policy "lottery stores are public"
  on public.lottery_stores for select using (true);

drop policy if exists "authenticated users register verified stores" on public.lottery_stores;
create policy "authenticated users register verified stores"
  on public.lottery_stores for insert to authenticated
  with check (
    id like 'kakao\_%' escape '\'
    or id like 'dhlottery\_%' escape '\'
    or id like 'osm\_%' escape '\'
  );

drop policy if exists "ranking snapshots are public" on public.ranking_snapshots;
create policy "ranking snapshots are public"
  on public.ranking_snapshots for select using (true);

drop policy if exists "system titles are public" on public.user_system_titles;
create policy "system titles are public"
  on public.user_system_titles for select using (true);

drop policy if exists "users manage own daily visits" on public.user_daily_visits;
create policy "users manage own daily visits"
  on public.user_daily_visits for all
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create or replace function public.refresh_monthly_rankings()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  current_period text := to_char(timezone('Asia/Seoul', now()), 'YYYY-MM');
begin
  delete from public.ranking_snapshots
  where period_key = current_period
    and ranking_type in ('purchase','accuracy','efficiency','miss','pioneer');

  insert into public.ranking_snapshots
    (period_key, ranking_type, user_id, rank, score, title, badge_icon, border_color)
  with ticket_scored as (
    select
      ticket.*,
      case when ticket.result = 'pending' then 0
        when jsonb_array_length(coalesce(game_results, '[]'::jsonb)) > 0
        then (select coalesce(sum((item ->> 'matched')::numeric), 0) from jsonb_array_elements(game_results) item)
        else coalesce(matched_count, 0)::numeric
      end as ticket_matches,
      case when ticket.result = 'pending' then 0
        when jsonb_array_length(coalesce(game_results, '[]'::jsonb)) > 0
        then (select count(*)::numeric from jsonb_array_elements(game_results) item where coalesce((item ->> 'matched')::integer, 0) = 0)
        else case when coalesce(matched_count, 0) = 0 then greatest(coalesce(game_count, 1), 1) else 0 end::numeric
      end as ticket_misses
    from public.tickets ticket
    where to_char(coalesce(purchase_date, (created_at at time zone 'Asia/Seoul')::date), 'YYYY-MM') = current_period
  ),
  ticket_base as (
    select
      user_id,
      sum(greatest(coalesce(game_count, 1), 1) * 1000)::numeric as spent,
      sum(coalesce(prize_amount, 0))::numeric as prize,
      sum(ticket_matches)::numeric as matches,
      sum(ticket_misses)::numeric as misses
    from ticket_scored
    group by user_id
  ),
  scores as (
    select user_id, metric.ranking_type, metric.score
    from ticket_base
    cross join lateral (values
      ('purchase', spent),
      ('accuracy', matches),
      ('efficiency', case when spent > 0 then round(prize * 100 / spent, 4) else 0 end),
      ('miss', misses)
    ) as metric(ranking_type, score)
    where metric.score > 0
  ),
  ranked as (
    select
      user_id,
      ranking_type,
      score,
      dense_rank() over (partition by ranking_type order by score desc)::integer as rank
    from scores
  )
  select
    current_period,
    ranking_type,
    user_id,
    rank,
    score,
    case ranking_type
      when 'purchase' then '구매'
      when 'accuracy' then '저격'
      when 'efficiency' then '수익'
      else '똥손'
    end,
    case ranking_type
      when 'purchase' then '👑'
      when 'accuracy' then '🎯'
      when 'efficiency' then '💸'
      else '💩'
    end,
    '#f5c451'
  from ranked;
end;
$$;

create or replace function public.refresh_all_time_rankings()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.ranking_snapshots
  where period_key = 'all'
    and ranking_type in ('donor','attendance','streak','scan','auto','manual','rank3','rank4','rank5');

  insert into public.ranking_snapshots
    (period_key, ranking_type, user_id, rank, score, title, badge_icon, border_color)
  with ticket_scored as (
    select
      ticket.user_id,
      greatest(coalesce(ticket.game_count, 1), 1)::numeric as games,
      coalesce(ticket.prize_amount, 0)::numeric as prize,
      ticket.purchase_mode,
      case when jsonb_array_length(coalesce(ticket.game_results, '[]'::jsonb)) > 0
        then (select count(*)::numeric from jsonb_array_elements(ticket.game_results) item where (item ->> 'rank')::integer = 3)
        else case when ticket.prize_rank = 3 then 1 else 0 end::numeric
      end as rank3_count,
      case when jsonb_array_length(coalesce(ticket.game_results, '[]'::jsonb)) > 0
        then (select count(*)::numeric from jsonb_array_elements(ticket.game_results) item where (item ->> 'rank')::integer = 4)
        else case when ticket.prize_rank = 4 then 1 else 0 end::numeric
      end as rank4_count,
      case when jsonb_array_length(coalesce(ticket.game_results, '[]'::jsonb)) > 0
        then (select count(*)::numeric from jsonb_array_elements(ticket.game_results) item where (item ->> 'rank')::integer = 5)
        else case when ticket.prize_rank = 5 then 1 else 0 end::numeric
      end as rank5_count
    from public.tickets ticket
  ),
  ticket_base as (
    select
      user_id,
      count(*)::numeric as scans,
      sum(games * 1000)::numeric as spent,
      sum(prize)::numeric as prize,
      sum(case when purchase_mode = 'auto' then games else 0 end)::numeric as auto_games,
      sum(case when purchase_mode = 'manual' then games else 0 end)::numeric as manual_games,
      sum(rank3_count)::numeric as rank3_count,
      sum(rank4_count)::numeric as rank4_count,
      sum(rank5_count)::numeric as rank5_count
    from ticket_scored
    group by user_id
  ),
  visit_grouped as (
    select
      user_id,
      visit_date,
      visit_date - (row_number() over (partition by user_id order by visit_date))::integer as streak_group
    from public.user_daily_visits
  ),
  visit_base as (
    select
      user_id,
      count(*)::numeric as attendance_days
    from public.user_daily_visits
    group by user_id
  ),
  visit_streaks as (
    select
      user_id,
      count(*)::numeric as streak_days
    from visit_grouped
    group by user_id, streak_group
  ),
  longest_streaks as (
    select user_id, max(streak_days)::numeric as longest_streak
    from visit_streaks
    group by user_id
  ),
  scores as (
    select user_id, metric.ranking_type, metric.score
    from ticket_base
    cross join lateral (values
      ('donor', greatest(spent - prize, 0)),
      ('scan', scans),
      ('auto', auto_games),
      ('manual', manual_games),
      ('rank3', rank3_count),
      ('rank4', rank4_count),
      ('rank5', rank5_count)
    ) as metric(ranking_type, score)
    where metric.score > 0

    union all

    select user_id, 'attendance', attendance_days
    from visit_base
    where attendance_days > 0

    union all

    select user_id, 'streak', longest_streak
    from longest_streaks
    where longest_streak > 0
  ),
  ranked as (
    select
      user_id,
      ranking_type,
      score,
      dense_rank() over (partition by ranking_type order by score desc)::integer as rank
    from scores
  )
  select
    'all',
    ranking_type,
    user_id,
    rank,
    score,
    case ranking_type
      when 'donor' then '기부왕'
      when 'attendance' then '출석왕'
      when 'streak' then '개근왕'
      when 'scan' then '스캔왕'
      when 'auto' then '자동왕'
      when 'manual' then '수동왕'
      when 'rank3' then '3등 콜렉터'
      when 'rank4' then '4등 콜렉터'
      else '5등 콜렉터'
    end,
    null,
    '#f5c451'
  from ranked;
end;
$$;

create or replace function public.refresh_monthly_rankings_after_ticket()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.refresh_monthly_rankings();
  perform public.refresh_all_time_rankings();
  return null;
end;
$$;

drop trigger if exists refresh_monthly_rankings_on_ticket on public.tickets;
create trigger refresh_monthly_rankings_on_ticket
  after insert or update or delete on public.tickets
  for each statement execute function public.refresh_monthly_rankings_after_ticket();

create or replace function public.refresh_all_time_rankings_after_visit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform public.refresh_all_time_rankings();
  return null;
end;
$$;

drop trigger if exists refresh_all_time_rankings_on_visit on public.user_daily_visits;
create trigger refresh_all_time_rankings_on_visit
  after insert or update or delete on public.user_daily_visits
  for each statement execute function public.refresh_all_time_rankings_after_visit();

grant execute on function public.refresh_monthly_rankings() to authenticated;
grant execute on function public.refresh_all_time_rankings() to authenticated;
